name: SonarQube - PR & Push Analysis

# Run on PRs and pushes to main
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    env:
      # Sonar host must be set in repo secrets (or point to sonarsource cloud)
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Sonar Scanner artifacts (optional)
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml', '**/build.gradle*') }}

      - name: Run build (for language specific instrumented coverage)
        # Build step depending on your stack: maven/gradle/npm/etc.
        run: |
          # Example for Gradle: ./gradlew clean build -x test
          echo "Insert your build commands here"

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # store admin or analysis token as secret
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          SONAR_PROJECT_KEY: org.example:my-repo
          SONAR_PROJECT_NAME: "My Repo"
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="${SONAR_HOST_URL}" \
            -e SONAR_TOKEN="${SONAR_TOKEN}" \
            -v "${{ github.workspace }}":/usr/src \
            -w /usr/src \
            sonarsource/sonar-scanner-cli:latest \
            -Dsonar.projectKey="${SONAR_PROJECT_KEY}" \
            -Dsonar.sources=. \
            -Dsonar.host.url="${SONAR_HOST_URL}" \
            -Dsonar.login="${SONAR_TOKEN}" \
            -Dsonar.pullrequest.key=${{ github.event.number || '' }} \
            -Dsonar.pullrequest.branch="${GITHUB_HEAD_REF:-}" \
            -Dsonar.pullrequest.base="${GITHUB_BASE_REF:-}"
