name: Synthetic Monitoring

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  synthetic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: node scripts/run_check.js scenarios/api_check.js
      - run: node scripts/run_check.js scenarios/homepage_check.js
      - run: node scripts/run_check.js scenarios/login_flow.js
      - run: node scripts/report_generator.js reports/*.json
      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: synthetic-monitoring-reports
          path: reports/
