replicaCount: 2

image:
  repository: your-registry/recommendation-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

env:
  REDIS_URL: redis://redis:6379/0
