# Elasticsearch cluster nodes, authentication, SSL configuration
elasticsearch:
  user: elastic
  password: strong_password_here
  nodes:
    - host: es-node-1.local
      port: 9200
    - host: es-node-2.local
      port: 9200
    - host: es-node-3.local
      port: 9200
  index_defaults:
    shards: 3
    replicas: 2
