# Detekt configuration file
# Detekt configuration for Kotlin static code analysis
# Advanced and production-ready
build:
  maxIssues: 10
  excludeCorrectable: false

processors:
  active: true
  exclude:
    - 'DetektProgressListener'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'

output-reports:
  active: true
  exclude: []
  formats:
    - 'xml'
    - 'html'
    - 'txt'

style:
  MagicNumber:
    active: true
    ignoreNumbers: '-1,0,1,2'
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true

  NamingRules:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'
    functionPattern: '[a-z][A-Za-z0-9]*'
    classPattern: '[A-Z][A-Za-z0-9]*'
    constantPattern: '[A-Z][_A-Z0-9]*'

complexity:
  LongMethod:
    active: true
    threshold: 50
  TooManyFunctions:
    active: true
    thresholdInClasses: 30
    thresholdInObjects: 20

comments:
  CommentOverPrivateFunction:
    active: true
  CommentOverPrivateProperty:
    active: true

# Include custom rule providers
custom:
  ForbiddenCommentRule:
    active: true
  CyclomaticComplexityRule:
    active: true
  NamingConventionRule:
    active: true
