# ====================================================
# Social Flow CLI - Config Template
# ====================================================
# This file provides a baseline YAML config that can be
# customized per environment (development, staging, prod).
# Copy this template to ~/.socialflow/config.yaml
# ====================================================

environment: development   # Options: development | staging | production
debug: false               # Enable detailed logs

api:
  base_url: "https://api.socialflow.local"
  timeout: 30
  retries: 3

auth:
  method: "oauth2"
  token_path: "~/.socialflow/token.json"

logging:
  level: "INFO"
  log_file: "~/.socialflow/cli.log"

plugins:
  enabled: true
  search_path:
    - "~/.socialflow/plugins"
    - "./plugins"
