name: Artillery Performance Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  artillery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd testing/performance/artillery
          npm ci

      - name: Prepare .env
        run: |
          cd testing/performance/artillery
          cp .env.example .env
          # Optionally set secrets via GitHub repo secrets in CI
          if [ -n "${{ secrets.BASE_URL }}" ]; then
            sed -i "s|BASE_URL=.*|BASE_URL=${{ secrets.BASE_URL }}|" .env
          fi

      - name: Run baseline scenario (short smoke)
        run: |
          cd testing/performance/artillery
          npm run test:baseline

      - name: Upload artifact (JSON report)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artillery-reports
          path: testing/performance/artillery/reports
