global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['localhost:9093']

  - job_name: 'recommendation-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8003', 'localhost:8003']

  - job_name: 'analytics-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8010']

  - job_name: 'app'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8000']

# Node/Exporter/service discovery can be added for k8s via kubernetes_sd_configs in prod.
