version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data
    networks:
      - sonarnet

  sonarqube:
    image: sonarqube:10.4-community
    # NOTE: choose a SonarQube image version appropriate for your environment.
    # For production, use supported/enterprise images and follow upgrade notes.
    depends_on:
      - db
    environment:
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      # Optional JVM tuning for local dev
      SONAR_WEB_JAVAOPTS: "-Xmx1g -Xms1g -XX:+HeapDumpOnOutOfMemoryError"
    ports:
      - "9000:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
    networks:
      - sonarnet

volumes:
  sonarqube-db-data:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:

networks:
  sonarnet:
    driver: bridge
