# Objective: Define routes, plugins, and upstreams for API management.
# Placeholder configuration
services:
  - name: user-service
    url: http://user-service:8080
    routes:
      - name: user-route
        paths:
          - /api/v1/users
plugins:
  - name: jwt
  - name: rate-limiting
