[tool.poetry]
name = "api-tests"
version = "0.1.0"
description = "Integration API tests for the project"
authors = ["Generated"]

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
