name: Gatling Performance Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  gatling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache sbt
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Build & run Gatling auth scenario (short)
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          USERS: 10
          RAMP_UP_SECONDS: 10
          DURATION_SECONDS: 20
        run: |
          cd testing/performance/gatling
          sbt -DbaseUrl=${BASE_URL} "gatling:testOnly simulations.AuthSimulation"

      - name: Upload results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gatling-results
          path: testing/performance/gatling/target/gatling/results
