name: Build and Push Images

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL || 'docker.io' }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push recommendation-service image
        env:
          REGISTRY: ${{ secrets.REGISTRY_URL || 'docker.io' }}
          REPO: ${{ secrets.REGISTRY_REPO || github.repository_owner }}
          TAG: ${{ github.sha }}
        run: |
          IMAGE=${REGISTRY}/${REPO}/recommendation-service:${TAG}
          docker buildx build --platform linux/amd64,linux/arm64 -t "${IMAGE}" \
            --push services/recommendation-service -f services/recommendation-service/Dockerfile || echo "No Dockerfile for recommendation-service"

      - name: Build and push app image (if present)
        env:
          REGISTRY: ${{ secrets.REGISTRY_URL || 'docker.io' }}
          REPO: ${{ secrets.REGISTRY_REPO || github.repository_owner }}
          TAG: ${{ github.sha }}
        run: |
          IMAGE=${REGISTRY}/${REPO}/app:${TAG}
          docker buildx build --platform linux/amd64,linux/arm64 -t "${IMAGE}" \
            --push app -f app/Dockerfile || echo "No Dockerfile for app"
