stages:
  - lint
  - test
  - build

variables:
  PYTHON_IMAGE: "python:3.11-slim"

lint:
  stage: lint
  image: $PYTHON_IMAGE
  script:
    - python -m pip install --upgrade pip
    - pip install flake8 || true
    - flake8 || true
  rules:
    - if: $CI_PIPELINE_SOURCE

test:
  stage: test
  image: $PYTHON_IMAGE
  script:
    - python -m pip install --upgrade pip
    - pip install pytest || true
    - pytest -q || true
  artifacts:
    when: always
    reports:
      junit: report.xml
  rules:
    - if: $CI_PIPELINE_SOURCE

build:
  stage: build
  image: docker:24.0.2
  services:
    - docker:dind
  script:
    - docker build -t "${CI_REGISTRY_IMAGE}/recommendation-service:${CI_COMMIT_SHA}" services/recommendation-service || echo "No Dockerfile"
    - docker push "${CI_REGISTRY_IMAGE}/recommendation-service:${CI_COMMIT_SHA}" || echo "Push skipped"
  only:
    - main
