version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: socialflow
      POSTGRES_PASSWORD: socialflow
      POSTGRES_DB: socialflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
    volumes:
      - miniodata:/data

# Example local service placeholders. Replace `build` with real Dockerfiles.
  recommendation-service:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ..:/app:cached
    command: ["sh", "-c", "python -m uvicorn services.recommendation-service.src.main:app --host 0.0.0.0 --port 8003"]
    ports:
      - "8003:8003"
    depends_on:
      - redis

volumes:
  pgdata:
  miniodata:
