name: Messaging Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  messaging-tests:
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: confluentinc/cp-zookeeper:7.4.0
        ports: ["2181:2181"]
      kafka:
        image: confluentinc/cp-kafka:7.4.0
        depends_on: [zookeeper]
        ports: ["9092:9092"]
      rabbitmq:
        image: rabbitmq:3.10-management
        ports: ["5672:5672", "15672:15672"]
      redis:
        image: redis:7
        ports: ["6379:6379"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r testing/integration/messaging-tests/requirements.txt

      - name: Wait for brokers
        run: |
          echo "Waiting for Kafka/RabbitMQ/Redis to become ready..."
          # Simple sleep; for production replace with healthchecks
          sleep 20

      - name: Run tests
        env:
          KAFKA_BOOTSTRAP_SERVERS: kafka:9092
          RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
          REDIS_URL: redis://redis:6379/0
        run: |
          pytest testing/integration/messaging-tests/tests -q -n auto
