openapi: 3.0.0
info:
  title: Video Service API
  version: "1.0.0"
  description: Video upload, retrieval and metadata APIs
servers:
  - url: https://api.example.com/video
paths:
  /health:
    get:
      summary: Health check
      responses:
        "200":
          description: OK

  /upload:
    post:
      summary: Create a new video record and initiate upload
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                title:
                  type: string
                description:
                  type: string
      responses:
        "201":
          description: Video accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'

  /videos:
    get:
      summary: List videos (pagination)
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        "200":
          description: Video list
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Video'

  /videos/{video_id}:
    get:
      summary: Retrieve video metadata (and signed playback URL)
      parameters:
        - name: video_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Video metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
        "404":
          description: Not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Video:
      type: object
      properties:
        id:
          type: string
          example: vid_123
        title:
          type: string
        description:
          type: string
        uploader_id:
          type: string
        duration:
          type: number
          format: float
        uploaded_at:
          type: string
          format: date-time
        playback_url:
          type: string
          example: https://cdn.example.com/vid_123/playlist.m3u8
