apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
  labels:
    app: recommendation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
        - name: recommendation
          image: your-registry/recommendation-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003
          env:
            - name: REDIS_URL
              value: redis://redis:6379/0
            - name: RECOMMENDER_PORT
              value: "8003"
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 30
            periodSeconds: 20

---

apiVersion: v1
kind: Service
metadata:
  name: recommendation-svc
spec:
  selector:
    app: recommendation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8003
  type: ClusterIP
